# Generated by Django 3.0.5 on 2021-12-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20211228_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exam_type',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
