# Generated by Django 3.0.5 on 2021-12-28 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_status'),
        ('exam', '0008_course_exam_cwt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseWiseStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.QCourse')),
            ],
        ),
    ]
