# Generated by Django 3.0.5 on 2021-12-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20211229_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
