# Generated by Django 3.0.5 on 2021-12-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_auto_20211229_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
