# Generated by Django 3.0.5 on 2021-12-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_question_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
